version: "3.7"

services:
  yarn:
    image: yarn-lts-alpine
    container_name: yarn-meaningless
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
